syntax = "proto3";

package gateway.v1;

// 注册。
message RegisterRequest {
  string player_id = 1;
  string password = 2;
}

message RegisterReply {
  string player_id = 1;
}

// 登录。
message LoginRequest {
  string player_id = 1;
  string password = 2;
}

message LoginReply {
  string token = 1;
  string player_id = 2;
  int64 server_time_unix_ms = 3;
}

// 业务心跳。
message HeartbeatRequest {
  string token = 1;
  string player_id = 2;
  int64 ts = 3;
}

message HeartbeatReply {
  int64 ts = 1;
  uint64 server_time_unix_ms = 2;
}
